### ISSUE TITLE
Compatibility with the control net extension

### ISSUE THREAD

**Issue by anisssssssssss** [papuSpartan/stable-diffusion-webui-distributed#3]
Is this script compatible with the control net extension? because i get this issue:
ERROR    Failed to serialize payload:          ]8;id=135739;file:///kaggle/working/stable-diffusion-webui/extensions/stable-diffusion-webui-distributed/scripts/spartan/Worker.py\Worker.py]8;;\:]8;id=804663;file:///kaggle/working/stable-diffusion-webui/extensions/stable-diffusion-webui-distributed/scripts/spartan/Worker.py#331\331]8;;\
                             {'outpath_samples':                                
                             'outputs/txt2img-images',                          
                             'outpath_grids':                                   
                             'outputs/txt2img-grids', 'prompt':                 
                             'hjj', 'prompt_for_display': None,                 
                             'negative_prompt': '', 'styles': [],               
                             'seed': -1.0, 'subseed': -1,                       
                             'subseed_strength': 0,                             
                             'seed_resize_from_h': 0,                           
                             'seed_resize_from_w': 0,                           
                             'sampler_name': 'Euler a',                         
                             'batch_size': 1, 'n_iter': 2,                      
                             'steps': 20, 'cfg_scale': 7, 'width':              
                             512, 'height': 512, 'restore_faces':               
                             False, 'tiling': False,                            
                             'do_not_save_samples': False,                      
                             'do_not_save_grid': False,                         
                             'extra_generation_params': {},                     
                             'overlay_images': None, 'eta': None,               
                             'do_not_reload_embeddings': False,                 
                             'paste_to': None,                                  
                             'color_corrections': None,                         
                             'denoising_strength': None,                        
                             'sampler_noise_scheduler_override':                
                             None, 'ddim_discretize': 'uniform',                
                             's_min_uncond': 0, 's_churn': 0.0,                 
                             's_tmin': 0.0, 's_tmax': 1e+308,                   
                             's_noise': 1.0, 'override_settings':               
                             {},                                                
                             'override_settings_restore_afterwards              
                             ': True,                                           
                             'is_using_inpainting_conditioning':                
                             False, 'disable_extra_networks':                   
                             False, 'scripts': None,                            
                             'script_args': (6, False, False,                   
                             'LoRA', 'None', 1, 1, 'LoRA', 'None',              
                             1, 1, 'LoRA', 'None', 1, 1, 'LoRA',                
                             'None', 1, 1, 'LoRA', 'None', 1, 1,                
                             None, 'Refresh models',                            
                             <controlnet.py.UiControlNetUnit                    
                             object at 0x7adb935bca90>, False,                  
                             False, 'positive', 'comma', 0, False,              
                             False, '', '', 1, '', [], 0, '', [],               
                             0, '', [], True, False, False, False,              
                             0, None, False, 50), 'all_prompts':                
                             None, 'all_negative_prompts': None,                
                             'all_seeds': None, 'all_subseeds':                 
                             None, 'iteration': 0, 'is_hr_pass':                
                             False, 'enable_hr': False,                         
                             'hr_scale': 2, 'hr_upscaler':                      
                             'Latent', 'hr_second_pass_steps': 0,               
                             'hr_resize_x': 0, 'hr_resize_y': 0,                
                             'hr_upscale_to_x': 0,                              
                             'hr_upscale_to_y': 0, 'truncate_x':                
                             0, 'truncate_y': 0,                                
                             'applied_old_hires_behavior_to':                   
                             None}                                              
Exception in thread Thread-24 (request):
Traceback (most recent call last):
  File "/kaggle/working/stable-diffusion-webui/extensions/stable-diffusion-webui-distributed/scripts/spartan/Worker.py", line 332, in request
    raise e
  File "/kaggle/working/stable-diffusion-webui/extensions/stable-diffusion-webui-distributed/scripts/spartan/Worker.py", line 329, in request
    json.dumps(payload)
  File "/opt/conda/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/conda/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/conda/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/conda/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type UiControlNetUnit is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/opt/conda/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/kaggle/working/stable-diffusion-webui/extensions/stable-diffusion-webui-distributed/scripts/spartan/Worker.py", line 369, in request
    raise InvalidWorkerResponse(e)
scripts.spartan.Worker.InvalidWorkerResponse: Object of type UiControlNetUnit is not JSON serializable

**Comment by papuSpartan** [comment]
It isn't yet, controlnet uses its own separate API routes. I'll be adding support for it soon.

**Comment by papuSpartan** [comment]
It should at least warn about doing this now https://github.com/papuSpartan/stable-diffusion-webui-distributed/commit/d3b790d709c8081213dce195b1d7dd35b37538b9

**Comment by Oompahbrumply** [comment]
Thanks for this extension. I am about to run it now, and hope you can stick with this as all of this changes over the coming years. This really makes my day.

**Comment by papuSpartan** [comment]
I've got controlnet support working now, but still ironing out some kinks.

**Comment by anisssssssssss** [comment]
@papuSpartan Thanks!

**Comment by papuSpartan** [comment]
I'll keep this open since there are bound to be bugs related to it   once I release the update.

**Comment by papuSpartan** [comment]
I have added support for controlnet (and multi-unit controlnet). Multi-unit will only work though if you set the remote machine to allow more than one unit in its settings page on that machine. I don't think batch mode will work yet though, only single image.

**Comment by unphased** [comment]
Hey, also chiming in here with a huge thanks for working on this. I haven't quite tested your plugin yet but I'm going to be slaving my gaming PC as a test first and then will get to buying more GPUs if it works out well. As far as I can tell this is the approach to use right now to leverage multiple GPUs, (just run as many instances of webui as GPUs exist on the host) and the elegance of your approach means GPUs in other machines on the local network can also be leveraged. 

I have specific questions for you regarding controlnet. I will surely be testing them out and helping troubleshoot and develop if I can, if there are issues related to the following as I embark on testing out this extension.

- Does this work with controlnet tile usage? I have great results with Ultimate SD Upscaler using Controlnet tile for upscaling. I am not sure how it would work, ideally all controlnet tile workloads can be distributed to slaves so they can help but this may be a lot of extra development. So if not then I hope we can at least leverage slaves by batching up these kind of upscales a bit. I am not aware of how to do this normally yet (batch up to queue multiple controlnet tile upscales) but I'm sure a script can achieve it at least. Failing that, though, multigpu is still great for accelerating other workflow batches.
-  I have found in my experience running controlnet tile upscales that there tends to be a bit of down time, like a second or two, between each tile getting rendered. I think this would contribute a lot of repeated temperature oscillations due to the unstable GPU utilization. My idea is that if the answer to the above is that there is a way to distribute controlnet tile workloads across instances, can we please also get an option to allow each node to do two tiles at a time and stagger them a bit so we avoid stuff like this?
- The above point is not specific to controlnet tile workloads obviously, since it affects situations like XYZ plot checkpoint switching, there is GPU utilization downtime when models are being loaded, but there is batching and also little downtime taking place between batches. So for example with this I would hope that there is a way with something like XYZ plot checkpoint switching that we could intelligently distribute the work somehow, e.g. say we have 3 instances and 6 checkpoints are specified in the XYZ, each instance would render two checkpoints and only have to do a switch one time. 

Sorry for not having done more experimentation first before firing off questions, you just got me so excited with this that I couldn't wait.

**Comment by papuSpartan** [comment]
As things are at the moment, you should be able to use the tile model with control-net like you would another model like segmentation or so on. However, I'm not hijacking controlnet in such a way other than just to pass on the selected options to the slaves making up the rest of the worker pool. So, you **can** use cn tile on every node in your worker pool and get the associated benefits from each, but there isn't any sort of smart chunking logic in place for cn tiling.

**Comment by unphased** [comment]
Thank you for your response! I have been exploring even more today and my plate's gonna be full playing around with comfyui and i've learned also that easydiffusion is capable of multigpu as well. It's clear that the way to go right now is leverage each UI for what it's best at. So I think A1111 with your extension is likely to be a staple in the toolbox as well.
