### ISSUE TITLE
Enabling Thin Client Mode

### ISSUE THREAD

**Issue by christianarrer** [papuSpartan/stable-diffusion-webui-distributed#31]
How can i enable the 

Thin Client Mode in the config json.

Thanks

**Comment by papuSpartan** [comment]
> How can i enable the 
> 
> 
> 
> Thin Client Mode in the config json.
> 
> 
> 
> Thanks

Did changing it from the UI not work? There is a toggle checkbox on the settings page once the plugin is loaded. If that doesn't work the setting field should be generated in the config file by default and you can manually swap it to true.

**Comment by papuSpartan** [comment]
Have you tried launching with the debug argument and checking the logs? It could be a file permissions problem if the extension can't save to config.

**Comment by christianarrer** [comment]
> Have you tried launching with the debug argument and checking the logs? It could be a file permissions problem if the extension can't save to config.

Okay i will check that

**Comment by christianarrer** [comment]
I set the permissions for the config.json to 0777 and added the nginx www-data user to my stable diffiusion user group called ai.
Not working ...
Can is somehow stop it from creating the "master" entry manually.

**Comment by papuSpartan** [comment]
> I noticed that the workers both will report out of memory after some time

If you set batch size high enough you will eventually run out of memory, even if your driver supports swapping. 

> It seems to me it needs a batch size of at least 2.

Setting batch size to 1 is very often a worst case for this extension.  Setups where remote generation is significantly faster than local generation (and complement creation is enabled) though, mean that you will be saturating the faster remote card. 

Irrespective of setup though, you'll have a better experience if you follow two main guidelines:
1. If possible, have your local/master instance be your fastest one. Doing this gives you the advantage of being able to see image previews more quickly and being able to fallback to normal webui behavior with less loss of throughput.

2. Increase batch size before batch count. This extension parallelizes batches rather than meshing multiple accelerators to generate each singular image.

**Comment by christianarrer** [comment]
**It seems to work really good now.** - I have one windows machine (the stronger one) as master and the second windows machine as worker. A Linux gui with the Thin client option works not very well. The first solution is the better one.
