### ISSUE TITLE
interrupt slave

### ISSUE THREAD

**Issue by yggdrasil75** [papuSpartan/stable-diffusion-webui-distributed#4]
http://localhost:7860/docs#/default/interruptapi_sdapi_v1_interrupt_post
when you hit interrupt, it only interrupts the local process.

**Comment by papuSpartan** [comment]
If you're referring to the normal interrupt button not interrupting remotes I made it that way on purpose. I'll probably make it a setting eventually but the way it works now is if you want to interrupt your remote machines then you need to hit the interrupt all button under the extension drop-down. This is so that you can  let master finish and start a new generation by cancelling waiting on the others in the case of long generation time, remote OOM, or otherwise.

**Comment by yggdrasil75** [comment]
alright. I will use that. though I do agree that having the default action be toggleable would be better.

**Comment by papuSpartan** [comment]
I'll try and add that after I push controlnet stuff.

**Comment by papuSpartan** [comment]
https://github.com/papuSpartan/stable-diffusion-webui-distributed/commit/75fc6ab7a9b884e79abd9045ce9b358f26536214 It should act now as you were initially expecting. Let me know if there are any issues.
